library(dplyr)
data <- read.csv("household_power_consumption.txt",sep=';',na.strings='?')
data <- mutate(data,Date = (as.Date(Date,format="%d/%m/%Y")))
datasubset <- filter(data,Date==as.Date("2/1/2007",format="%m/%d/%Y") | Date==as.Date("2/2/2007",format="%m/%d/%Y"))
datasubset <- mutate(datasubset,DateTime=as.POSIXct(strptime(paste(Date,Time),format="%Y-%m-%d %H:%M:%S")))
plot(datasubset$DateTime,datasubset$Sub_metering_1,ylab="Energy sub metering",xlab="",type="n")
lines(datasubset$DateTime,datasubset$Sub_metering_1)
lines(datasubset$DateTime,datasubset$Sub_metering_2,col="red")
lines(datasubset$DateTime,datasubset$Sub_metering_3,col="blue")
legend("topright",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lwd=1)
dev.copy(png,filename="plot3.png",width=480,height=480)
dev.off()
