library(dplyr)
data <- read.csv("household_power_consumption.txt",sep=';',na.strings='?')
data <- mutate(data,Date = (as.Date(Date,format="%d/%m/%Y")))
datasubset <- filter(data,Date==as.Date("2/1/2007",format="%m/%d/%Y") | Date==as.Date("2/2/2007",format="%m/%d/%Y"))
datasubset <- mutate(datasubset,DateTime=as.POSIXct(strptime(paste(Date,Time),format="%Y-%m-%d %H:%M:%S")))
hist(datasubset$Global_active_power,col="red",breaks=12,xlab="Global Active Power (kilowatts)",main="Global Active Power")
dev.copy(png,filename="plot1.png",width=480,height=480)
dev.off()
